import { ContactForm } from "./contact-form"

const environments = ["NVIDIA GPUs", "vLLM", "NVIDIA NIM", "TensorRT-LLM", "Triton", "Ray", "Kubernetes", "Slurm"]
const gpuMetrics = ["GPU energy consumption", "GPU utilization", "HBM activity", "Memory-bound behavior", "Performance per watt", "GPU time per workload", "Thermal behavior", "Workload SLA impact"]
const contextMetrics = ["Exact input tokens", "Atomic task budgets", "Context growth", "Loop detection", "Tool calls", "Retries", "Audit verification"]
const contextFlow = [
  ["01", "COUNT", "Exact model tokenizer"],
  ["02", "BUDGET", "Reserve task budget atomically"],
  ["03", "COMPACT", "Remove only permitted old context"],
  ["04", "ENFORCE", "Block loops and hard-limit violations, then record a verifiable audit event"],
]

export default function Page() {
  return <>
    <nav><div className="nav-inner"><a className="logo" href="#hero">BZICHIMEM<span>_</span></a><div className="nav-links"><a className="nav-link" href="#hbmguard">HBMGuard</a><a className="nav-link" href="#contextguard">ContextGuard</a><a className="nav-link" href="#arch">Architecture</a><a className="btn-nav" href="#contact">Request Pilot</a></div></div></nav>
    <main>
      <section id="hero"><div className="container"><div className="hero-grid"><div className="hero-copy">
        <p className="eyebrow">AI Infrastructure Efficiency</p><h1><span className="hero-brand">HBMGuard</span></h1>
        <h2 className="hero-headline">Reduce GPU Energy.<br />Then Control the Context.</h2>
        <p className="hero-sub">Infrastructure-aware optimization for private AI — from GPU, HBM and power to agents, context and tokens.</p>
        <div className="hero-ctas"><a className="btn-primary" href="#contact">Request an HBMGuard Pilot</a><a className="btn-secondary" href="#contextguard">Explore ContextGuard</a></div>
        <p className="hero-evidence">20.47% mean GPU-energy reduction · Replicated A100 KV-cache qualification · &lt;1% throughput impact · workload-specific results</p>
        <div className="stack-line"><span>GPU / HBM / Power</span><b>↑</b><strong>HBMGuard</strong><b>↑</b><span>Context / Tokens / Loops</span><b>↑</b><strong>ContextGuard</strong></div>
        <p className="hero-note">Built for private, on-prem and security-sensitive AI environments.</p>
      </div><div className="hero-telemetry"><div className="terminal-strip"><div className="terminal-bar"><div className="dot dot-r" /><div className="dot dot-y" /><div className="dot dot-g" /><span className="term-title">hbmguard_agent · node-a100-01 · live</span></div><div className="terminal-body"><div><span className="t-dim">[2026-06-18 08:41:03]</span> <span className="t-white">HBMGuard v0.9 — DCGM Profiling API connected</span></div><div><span className="t-dim">[08:41:05]</span> <span className="t-white">SM_CLOCK: 1410 MHz DRAM_ACTIVE: 94% PWR: 398W</span> <span className="t-amber">⚠ Memory Wall detected</span></div><div><span className="t-dim">[08:41:05]</span> <span className="t-red">ECO_CTRL: applying workload-aware power policy</span></div><div><span className="t-dim">[08:41:14]</span> <span className="t-amber">HBM telemetry: threshold crossed → controlled response</span></div><div><span className="t-dim">[08:42:31]</span> <span className="t-green">✓ Node healthy. Workload restored. Engineers paged: 0.</span> <span className="blink t-dim">█</span></div></div></div></div></div></div></section>

      <section id="hbmguard"><div className="container"><p className="eyebrow">Primary capability · HBMGuard</p><h2>HBMGuard — GPU Infrastructure <em>Efficiency</em></h2><p className="section-lede">AI infrastructure efficiency begins below the model layer. HBMGuard observes and optimizes the physical behavior of GPU workloads using hardware telemetry, workload measurements and controlled GPU power policies.</p><div className="metric-layout"><div className="metric-list"><h3>HBMGuard focuses on</h3>{gpuMetrics.map((m) => <div className="metric-item" key={m}><span className="arch-dot" />{m}</div>)}</div><div className="kpi-card"><span className="kpi-label">Primary KPI</span><strong>Energy / Successful Workload <em>↓</em></strong><span className="kpi-label">Secondary KPI</span><strong>Performance per Watt <em>↑</em></strong></div></div></div></section>

      <section id="evidence"><div className="container"><p className="eyebrow">Validated result · workload-specific</p><h2>Evidence-backed GPU <em>efficiency</em></h2><div className="evidence-grid"><div className="evidence-number"><strong>20.47%</strong><span>mean GPU-energy reduction</span><small>Replicated A100 KV-cache qualification</small></div><div className="evidence-number"><strong>&lt;1%</strong><span>throughput impact</span><small>measured within the qualification workload</small></div></div><p className="qualification">Results are workload-specific and must be independently qualified for each customer environment. No universal savings are implied.</p></div></section>

      <section id="contextguard"><div className="container"><p className="eyebrow">Secondary capability · ContextGuard</p><h2>Control the Context. <em>Protect the Task.</em></h2><p className="section-lede">ContextGuard is a deterministic enforcement gateway between AI agents and an OpenAI-compatible model endpoint. It provides exact model-token accounting, atomic per-task budgets, safe context compaction, repeated-request loop protection, hard input-budget enforcement with no silent truncation, and tamper-evident HMAC audit verification.</p><div className="agent-grid"><div><h3>Agent / context efficiency and safety</h3><p className="body-copy">ContextGuard keeps AI agents within explicit token, loop, and audit boundaries before requests reach the model. It reduces unnecessary context while preserving required information and gives operators a verifiable decision trail.</p><p className="objective">The objective is not simply fewer tokens.<br /><strong>Resources per Successful Task.</strong></p></div><div className="metric-list"><h3>ContextGuard enforces</h3>{contextMetrics.map((m) => <div className="metric-item" key={m}><span className="arch-dot" />{m}</div>)}</div></div></div></section>

      <section id="context-evidence"><div className="container"><div className="trace-panel"><div className="trace-head"><span>Controlled A100 demonstration — workload-specific</span><span className="t-green">● evidence panel</span></div><div className="trace-grid context-evidence-grid"><div><span>MODEL</span><strong>Qwen2.5-7B-Instruct</strong></div><div><span>HARDWARE</span><strong>NVIDIA A100-SXM4-40GB</strong></div><div><span>ORIGINAL INPUT</span><strong>1,781 tokens</strong></div><div><span>FORWARDED INPUT</span><strong>216 tokens</strong></div><div><span>INPUT SAVED</span><strong>1,565 tokens</strong></div><div><span>CONTROLLED-DEMO REDUCTION</span><strong className="t-green">87.87%</strong></div><div><span>MODEL FAILURES</span><strong>0</strong></div><div><span>AUDIT</span><strong>HMAC verified</strong></div><div><span>TOKENIZER</span><strong>exact via vLLM /tokenize</strong></div></div><small>Demonstration result from one controlled workload; it is not a universal savings guarantee. Customer environments require independent qualification.</small></div></div></section>

      <section id="workflow"><div className="container"><h2>ContextGuard flow, <em>enforced</em></h2><div className="flow-steps">{contextFlow.map(([n, t, p]) => <div className="flow-step" key={n}><div className="step-num">{n}</div><div className="step-body"><span className="step-tag">{t}</span><p>{p}</p></div></div>)}</div></div></section>

      <section id="arch"><div className="container"><h2>Full-stack <em>architecture</em></h2><div className="architecture"><div className="arch-layer">APPLICATION / AGENTS<small>AI applications and agent workflows</small></div><div className="arch-arrow">↓</div><div className="arch-layer complementary">CONTEXTGUARD / TOKENS / LOOPS / AUDIT<small>Deterministic gateway · budgets · compaction · HMAC audit</small></div><div className="arch-arrow">↓</div><div className="arch-layer">INFERENCE / MODEL / KV CACHE<small>OpenAI-compatible model endpoint</small></div><div className="arch-arrow">↓</div><div className="arch-layer primary-layer">HBMGUARD / GPU / HBM / POWER<small>Physical workload efficiency and telemetry</small></div></div></div></section>

      <section id="private"><div className="container"><p className="eyebrow">Deployment model</p><h2>Built for <em>Private AI Infrastructure</em></h2><p className="section-lede">BZICHIMEM is designed for environments where sensitive application data should remain inside the customer&apos;s controlled environment.</p><div className="private-grid"><div className="problem-card"><h3>Metadata-only assessment mode</h3><p>Prompts, documents, RAG content and model responses can remain inside the customer&apos;s environment.</p></div><div className="problem-card"><h3>Operational telemetry</h3><p>Token counts · context size · agent-step counts · tool-call counts · retry counts · latency · cache statistics · GPU utilization · HBM telemetry · power consumption.</p></div></div><div className="environment-label">Designed to integrate with</div><div className="pills">{environments.map((e) => <span key={e}>{e}</span>)}</div></div></section>

      <section id="pilot"><div className="container"><h2>Start with GPU Efficiency.<br /><em>Expand to Agent Efficiency.</em></h2><div className="pilot-grid"><PilotCard title="HBMGuard GPU Efficiency Pilot" items={["GPU / HBM / power telemetry", "Workload profiling", "Controlled optimization", "A/B validation"]} outputs={["Energy / workload", "GPU time / workload", "Performance-per-watt", "SLA impact"]} /><PilotCard title="ContextGuard Agent Efficiency Assessment" items={["Exact token accounting", "Atomic budget enforcement", "Context compaction", "Loop and audit verification"]} outputs={["Tokens / successful task", "Forwarded context", "Model failures", "Potential optimization areas"]} /></div></div></section>

      <section id="contact"><div className="container"><div className="cta-box"><p className="eyebrow">Evidence-gated optimization · private deployment</p><h2>Optimize the Infrastructure First.<br /><em>Then Optimize the Agent.</em></h2><p>BZICHIMEM connects AI software behavior with the physical infrastructure running it.</p><ContactForm /></div></div></section>
    </main>
    <footer><div className="container"><div className="footer-inner"><div className="footer-logo">BZICHIMEM — AI Infrastructure Efficiency<br /><span>HBMGuard + ContextGuard</span></div><div className="footer-links"><a href="mailto:contact@bzichimem.com">contact@bzichimem.com</a><span>Private deployment</span><span>Metadata-first assessment</span></div></div></div></footer>
  </>
}

function PilotCard({ title, items, outputs }: { title: string; items: string[]; outputs: string[] }) {
  return <div className="pilot-card"><h3>{title}</h3><span className="card-label">BASELINE</span>{items.map((item) => <div className="metric-item" key={item}><span className="arch-dot" />{item}</div>)}<span className="card-label">OUTPUT</span><div className="output-list">{outputs.map((output) => <span key={output}>{output}</span>)}</div></div>
}
