import { ContactForm } from "./contact-form"

const environments = ["NVIDIA GPUs", "vLLM", "NVIDIA NIM", "TensorRT-LLM", "Triton", "Ray", "Kubernetes", "Slurm"]
const gpuMetrics = ["GPU energy consumption", "GPU utilization", "HBM activity", "Memory-bound behavior", "Performance per watt", "GPU time per workload", "Thermal behavior", "Workload SLA impact"]
const agentMetrics = ["Input tokens", "Output tokens", "Context growth", "Repeated context", "Agent steps", "Tool calls", "Retries", "Cache usage", "Model usage", "Latency", "Task success rate"]

export default function Page() {
  return <>
    <nav><div className="nav-inner"><a className="logo" href="#hero">BZICHIMEM<span>_</span></a><div className="nav-links"><a className="nav-link" href="#hbmguard">HBMGuard</a><a className="nav-link" href="#agent">Agent Efficiency</a><a className="nav-link" href="#arch">Architecture</a><a className="btn-nav" href="#contact">Request Pilot</a></div></div></nav>

    <main>
      <section id="hero"><div className="container"><div className="hero-grid"><div className="hero-copy">
        <p className="eyebrow">AI Infrastructure Efficiency</p>
        <h1><span className="hero-brand">HBMGuard</span></h1>
        <h2 className="hero-headline">Reduce GPU Energy.<br />Then Reduce Agent Token Waste.</h2>
        <p className="hero-sub">Infrastructure-aware optimization for private AI — from GPU, HBM and power to agents, context and tokens.</p>
        <div className="hero-ctas"><a className="btn-primary" href="#contact">Request an HBMGuard Pilot</a><a className="btn-secondary" href="#agent">Explore Agent Efficiency</a></div>
        <p className="hero-evidence">20.47% mean GPU-energy reduction in replicated A100 qualification · &lt;1% throughput impact · workload-specific results</p>
        <div className="stack-line"><span>GPU / HBM / Power</span><b>↑</b><strong>HBMGuard</strong><b>↑</b><span>Model / KV Cache</span><b>↑</b><span>Agent / Context / Tokens</span></div>
        <p className="hero-note">Built for private, on-prem and security-sensitive AI environments.</p>
      </div><div className="hero-telemetry"><div className="terminal-strip"><div className="terminal-bar"><div className="dot dot-r" /><div className="dot dot-y" /><div className="dot dot-g" /><span className="term-title">hbmguard_agent · node-a100-01 · live</span></div><div className="terminal-body"><div><span className="t-dim">[2026-06-18 08:41:03]</span> <span className="t-white">HBMGuard v0.9 — DCGM Profiling API connected</span></div><div><span className="t-dim">[08:41:05]</span> <span className="t-white">SM_CLOCK: 1410 MHz DRAM_ACTIVE: 94% PWR: 398W</span> <span className="t-amber">⚠ Memory Wall detected</span></div><div><span className="t-dim">[08:41:05]</span> <span className="t-red">ECO_CTRL: applying workload-aware power policy</span></div><div><span className="t-dim">[08:41:14]</span> <span className="t-amber">HBM telemetry: threshold crossed → controlled response</span></div><div><span className="t-dim">[08:42:31]</span> <span className="t-green">✓ Node healthy. Workload restored. Engineers paged: 0.</span> <span className="blink t-dim">█</span></div></div></div></div></div>
      </div></section>

      <section id="hbmguard"><div className="container"><p className="eyebrow">Primary capability · HBMGuard</p><h2>HBMGuard — GPU Infrastructure <em>Efficiency</em></h2><p className="section-lede">AI infrastructure efficiency begins below the model layer. HBMGuard observes and optimizes the physical behavior of GPU workloads using hardware telemetry, workload measurements and controlled GPU power policies.</p><div className="metric-layout"><div className="metric-list"><h3>HBMGuard focuses on</h3>{gpuMetrics.map((m) => <div className="metric-item" key={m}><span className="arch-dot" />{m}</div>)}</div><div className="kpi-card"><span className="kpi-label">Primary KPI</span><strong>Energy / Successful Workload <em>↓</em></strong><span className="kpi-label">Secondary KPI</span><strong>Performance per Watt <em>↑</em></strong></div></div></div></section>

      <section id="evidence"><div className="container"><p className="eyebrow">Validated result · workload-specific</p><h2>Evidence-backed GPU <em>efficiency</em></h2><div className="evidence-grid"><div className="evidence-number"><strong>20.47%</strong><span>mean GPU-energy reduction</span><small>in replicated A100 KV-cache qualification</small></div><div className="evidence-number"><strong>&lt;1%</strong><span>throughput impact</span><small>measured within the qualification workload</small></div></div><p className="qualification">Results are workload-specific and must be independently qualified for each customer environment. No universal savings are implied.</p></div></section>

      <section id="workflow"><div className="container"><h2>The control loop, <em>explained</em></h2><div className="flow-steps">{[["01","OBSERVE","Collect GPU telemetry, workload performance, HBM behavior and power measurements."],["02","DIAGNOSE","Identify inefficient operating regions, memory-bound behavior and workload/power mismatches."],["03","CONTROL","Apply workload-aware GPU operating policies within predefined safety and SLA constraints."],["04","VERIFY","Compare optimized execution against baseline and confirm SLA-safe restoration to baseline state."]].map(([n,t,p]) => <div className="flow-step" key={n}><div className="step-num">{n}</div><div className="step-body"><span className="step-tag">{t}</span><p>{p}</p></div></div>)}</div><div className="metric-ribbon"><span>GPU energy ↓</span><span>GPU time ↓</span><span>Performance per watt ↑</span><span>Throughput within SLA</span><span>Latency within SLA</span></div></div></section>

      <section id="agent"><div className="container"><p className="eyebrow">Secondary capability · pilot / assessment</p><h2>Extend Efficiency <em>Above the GPU</em></h2><div className="agent-grid"><div><h3>Agent Efficiency</h3><p className="section-lede">Once infrastructure efficiency is understood, BZICHIMEM extends measurement into agent workloads — tracking unnecessary context, retries, tool calls, cache inefficiency and token consumption.</p><p className="body-copy">Modern AI agents may consume unnecessary resources through repeated context, oversized histories, unnecessary tool calls, retry chains, repeated tool outputs, agent loops, inefficient model selection and poor cache reuse.</p><p className="objective">The objective is not simply fewer tokens.<br /><strong>Resources per Successful Task.</strong></p></div><div className="metric-list"><h3>Measure</h3>{agentMetrics.map((m) => <div className="metric-item" key={m}><span className="arch-dot" />{m}</div>)}<div className="kpi-mini">Tokens / Successful Task ↓<br />GPU-seconds / Successful Task ↓</div></div></div></div></section>

      <section id="trace"><div className="container"><div className="trace-panel"><div className="trace-head"><span>Agent Efficiency Trace</span><span className="t-green">● illustrative</span></div><div className="trace-grid"><div><span>WORKFLOW</span><strong>agent-prod-07</strong></div><div><span>TASK STATUS</span><strong className="t-green">SUCCESS</strong></div><div><span>INPUT TOKENS</span><strong>84,200</strong></div><div><span>REPEATED CONTEXT</span><strong>31%</strong></div><div><span>AGENT STEPS</span><strong>14</strong></div><div><span>TOOL CALLS</span><strong>11</strong></div><div><span>RETRIES</span><strong>3</strong></div><div><span>GPU TIME</span><strong>38.4 sec</strong></div></div><div className="opportunities"><span>EFFICIENCY OPPORTUNITIES</span><p>↳ Repeated context detected</p><p>↳ Tool-result replay detected</p><p>↳ Retry chain detected</p></div><small>Illustrative workflow example — not customer evidence.</small></div></div></section>

      <section id="arch"><div className="container"><h2>Full-stack <em>architecture</em></h2><div className="architecture"><div className="arch-layer">APPLICATION<small>Agents / RAG / Tools</small></div><div className="arch-arrow">↓</div><div className="arch-layer complementary">AGENT EFFICIENCY<small>Tokens / Context / Cache / Steps</small></div><div className="arch-arrow">↓</div><div className="arch-layer">INFERENCE<small>Model / KV Cache</small></div><div className="arch-arrow">↓</div><div className="arch-layer primary-layer">HBMGUARD<small>GPU / HBM / Power / Thermal</small></div><div className="arch-arrow">↓</div><div className="arch-layer business">BUSINESS METRICS<small>Energy / Task · GPU Time / Task · Tokens / Task · Cost / Task · SLA</small></div></div></div></section>

      <section id="private"><div className="container"><p className="eyebrow">Deployment model</p><h2>Built for <em>Private AI Infrastructure</em></h2><p className="section-lede">BZICHIMEM is designed for environments where sensitive application data should remain inside the customer&apos;s controlled environment.</p><div className="private-grid"><div className="problem-card"><h3>Metadata-only assessment mode</h3><p>Prompts, documents, RAG content and model responses can remain inside the customer&apos;s environment.</p></div><div className="problem-card"><h3>Operational telemetry</h3><p>Token counts · context size · agent-step counts · tool-call counts · retry counts · latency · cache statistics · GPU utilization · HBM telemetry · power consumption.</p></div></div><div className="pills">{environments.map((e) => <span key={e}>{e}</span>)}</div></div></section>

      <section id="pilot"><div className="container"><h2>Start with GPU Efficiency.<br /><em>Expand to Agent Efficiency.</em></h2><div className="pilot-grid"><PilotCard title="HBMGuard Pilot" items={["GPU / HBM / power telemetry","Workload profiling","Controlled optimization","A/B validation"]} outputs={["Energy / workload","GPU time / workload","Performance-per-watt","SLA impact"]} /><PilotCard title="Agent Efficiency Assessment" items={["Token accounting","Context analysis","Agent-step analysis","Cache / retry analysis","A/B validation"]} outputs={["Tokens / successful task","GPU-seconds / successful task","Latency","Task success rate","Potential optimization areas"]} /></div></div></section>

      <section id="contact"><div className="container"><div className="cta-box"><p className="eyebrow">Evidence-gated optimization · private deployment</p><h2>Optimize the Infrastructure First.<br /><em>Then Optimize the Agent.</em></h2><p>BZICHIMEM connects AI software behavior with the physical infrastructure running it.</p><ContactForm /></div></div></section>
    </main>
    <footer><div className="container"><div className="footer-inner"><div className="footer-logo">BZICHIMEM — AI Infrastructure Efficiency<br /><span>HBMGuard + Agent Efficiency</span></div><div className="footer-links"><a href="mailto:contact@bzichimem.com">contact@bzichimem.com</a><span>Private deployment</span><span>Metadata-first assessment</span></div></div></div></footer>
  </>
}

function PilotCard({ title, items, outputs }: { title: string; items: string[]; outputs: string[] }) {
  return <div className="pilot-card"><h3>{title}</h3><span className="card-label">BASELINE</span>{items.map((item) => <div className="metric-item" key={item}><span className="arch-dot" />{item}</div>)}<span className="card-label">OUTPUT</span><div className="output-list">{outputs.map((output) => <span key={output}>{output}</span>)}</div></div>
}
